### ISSUE TITLE
Bug: Changes in color of the light when not instructed.

### ISSUE THREAD

**Issue by jprgomet** [athombv/com.lifx#14]
**Context – what were you trying to achieve?**
Change brightness in a flow.

**Detailed steps to reproduce the error from scratch.**
I have a light color set via LIFX iOS app, at 3200K.
And for e.g. I have Kodi app that changes brightness on pause/resume. 30% of the time when changing brightness it changes light color to high, like 9000K. After few more play/resume it brings the color back, but I don't know is it Homey or iOS app, that sets the color back to 3200K.

When you open LIFX device on Homey Mobile app v2, you can see that the color is set incorrectly.
It shows 9000K when I set 2700K in iOS app, and when I change in iOS to 9000K Homey reads change after few sec and shows that is totally yellow 2700K (circle on right side of bar in Homey app).

When I set 6500K in iOS app Homey shows circle in the middle, so that looks correct.

I think Homey LIFX device show opposite white color from LIFX set color.

**Comment by RobinBol** [comment]
What version of the LIFX app for Homey do you use?

In general, it is recommended to only use the Homey smartphone app to control the LIFX lights, not the LIFX smartphone app itself. This can cause values to get out of sync which might cause this issue.

**Comment by jprgomet** [comment]
I use latest 2.0.6.

Maybe, I will try using only Homey LIFX app.

**Comment by moekdegroot** [comment]
Hi @RobinBol ,
Just wanted to chip in for a moment.
I just want to point out that I don't think this bug is related to 3rd party apps also controlling the lifx lights besides homey.
Homey always shows that my lights are set in a cold white when I first open the control window in Chrome or in the Homey app, even though the only white I use in the house is warm white.
As soon as I change the brightness the light actually sets itself to cold white.
Then sometimes when you change the brightness again or switch views (for instance from temp to hue and back again) the lights changes back to warm white.
So in order to change the brightness manually you HAVE to use a third party app because else it won't work as it should.
Currently I only control the lifx lights with  through flows and  if the flow contains a "set brightness" card I always add a "set temperature"card aswel to make sure the light doesn't jump to cold white.
You managed to add the polling just before you went on a holiday, which was really appreciated!!!
But I think it needs some more work.
Best, Moek

**Comment by WeeJeWel** [comment]
Fixed in the rewrite
